---
dependencies:
  - wget
  - certbot
  - build-essential
  - libreadline-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - libffi-dev
  - zlib1g-dev
  - python3-venv
  - python3-pip
  - virtualenv
  - python3-virtualenv
  - python3-psycopg2
